### ISSUE TITLE
Draw ROC Curves

### ISSUE THREAD

**Issue by linan7788626** [milesxu/SSLDeepLens#4]
Need more discussion about this script

https://github.com/milesxu/SSLDeepLens/blob/master/generate_roc_curve.py

**Comment by linan7788626** [comment]
@milesxu I think we should make a plot the ROC curve with xrange(0,1) and yrange(0.1) to take a look at the shape of the curve first. Can you please draw the plot and post here? Thanks

**Comment by milesxu** [comment]
![roc_curve](https://user-images.githubusercontent.com/2003731/59965266-3fa80e00-953e-11e9-88fb-f57a8b1a4c11.png)
I have changed plt.xlim and ylim. The result is above.

**Comment by linan7788626** [comment]
Thanks for the update, it looks reasonable to me, let see whether there would be any improvement with the new approach of preprocessing. BTW, I attached the table of the results of the entries in the lens finding challenge, if you could please list the Area under the ROC, then we can evaluate our outcome more straightforwardly. In this case, we should compare our results to that of ground-based telescopes in the table. 

<img width="1169" alt="Screenshot 2019-06-22 at 16 00 17" src="https://user-images.githubusercontent.com/1016652/59965582-ff2d9d80-9507-11e9-8817-6bde4eaa2d5f.png">

**Comment by linan7788626** [comment]
Hello @milesxu, just a gentle inquiry, is there any progress about this? BTW, can you please also take a look at the pull request I submitted days ago #5 , thanks a lot.

All the best,
Nan

**Comment by milesxu** [comment]
![roc_curve_2019-09-09-14-46-53](https://user-images.githubusercontent.com/2003731/64509153-b53ba300-d311-11e9-9ba1-5e0c3fbc36ef.png)
I have changed the code to use sklearn to compute ROC arrays and then plot them.
Now I am trying to figure out how to compute TPR0 and TPR10.

**Comment by linan7788626** [comment]
@milesxu I am closing this issue because this one is updated to #6 now. Please feel free to reopen it if needed.
